### ISSUE TITLE
Drop down is empty

### ISSUE THREAD

**Issue by LucasBrazi06** [osahner/ngx-i18n-country-select#1]
I did the setup as you described and the dropdown is shown empty (only 'please choose' is shown.)	

"angular/animations": "^5.0.0",
"angular/common": "^5.0.1",
"angular/compiler": "^5.0.1",
"angular/core": "^5.0.1",
"angular/forms": "^5.0.1",
"angular/http": "^5.0.1",
"angular/platform-browser": "^5.0.0",
"angular/platform-browser-dynamic": "^5.0.0",
"angular/router": "^5.0.0",
"bootstrap": "^4.0.0",
"i18n-iso-countries": "^3.4.0",

Could you please check?
Thanks.

**Comment by osahner** [comment]
Hi Lucas,

I am afraid you have to downgrade i18n-iso-countries to ^2.1.1. 
`npm install 18n-iso-countries@^2.1.0 --save`
Version 3 has a new Structure, and by now I've had no time to check and implement.

Sorry for that
