### ISSUE TITLE
TS error : "default_label is private" when using "ng build --prod"

### ISSUE THREAD

**Issue by YoanDieu** [osahner/ngx-i18n-country-select#3]
Hi there. 

When running `ng build --prod` in my project I'm noticing the following error:

`ERROR in Error at /Users/yoan/Cstar/Telephone/telephone-faq-admin/node_modules/ngx-i18n-country-select/ngx-i18n-country-select.d.ts.I18nCountrySelectComponent.html(4,32): Property 'defaultLabel' is private and only accessible within class 'I18nCountrySelectComponent'.`

It's probably just what it says, as the property is indeed set as private but is used in the template. I tried to make a fork to fix it for myself and propose a PR. But installing my fork with npm provoc all kinds of errors because of packaging. I tried to add `"prepare": "gulp build"` in the package.json, but still no luck.

Would you be able to make the fix yourself? If not, would you be able for merging a PR en publishing it to npm if i make one?

Thanks.

**Comment by osahner** [comment]
fixed in v1.2.2

Thanks for this note!

**Comment by YoanDieu** [comment]
And it builds ! Thank you sire !
